[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
    [".config/tmux/plugins/tpm".pull]
        args = ["--ff-only"]

[".local/share/zinit/zinit.git"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]

['{{ (env "WORKSPACE_DIR") | trimPrefix (env "HOME") | trimPrefix "/" }}/alecharp/toolbox']
    type = "git-repo"
    url = "https://github.com/alecharp/toolbox.git"
    clone.args = ["--depth", "1"]
