worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[commit.generation]
command = "opencode run -m anthropic/claude-haiku-4.5 --variant fast"

[switch]
cd = true

[aliases]
sw = "switch"

[post-switch]
tmux = "[ -n \"$TMUX\" ] && tmux rename-window {{ branch | sanitize }}"

